# Generated by Django 4.1.3 on 2022-11-09 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country name')),
                ('code', models.CharField(max_length=2, verbose_name='Country code')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='University name')),
                ('acronym', models.CharField(max_length=10, verbose_name='University acronym')),
                ('logo', models.ImageField(upload_to='images/univercity_logos', verbose_name='University logo')),
                ('type', models.CharField(max_length=100, verbose_name='University type')),
                ('overview', models.TextField(verbose_name='University overview')),
                ('since', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='University since')),
                ('total_students', models.IntegerField(verbose_name='Total students')),
                ('international_students', models.IntegerField(verbose_name='International students')),
                ('website_url', models.URLField(verbose_name='University website url')),
                ('acceptance_rate', models.IntegerField(verbose_name='Acceptance rate')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='university.city', verbose_name='City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='university.country', verbose_name='Country'),
        ),
    ]
